// Generated by Selenium IDE

import junit.framework.TestCase;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;

import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.util.HashMap;
import java.util.Iterator;
import java.util.Map;

public class ReqTest {
    private WebDriver driver;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        System.setProperty("webdriver.chrome.driver", "C:/Program Files (x86)/Google/chromedriver.exe");
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        Map<String, Object> vars = new HashMap<>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void readXlsx() throws IOException {
        String filepath = "D:\\OneDrive\\OneDrive - tju.edu.cn\\寒假学习笔记\\软件测试技术\\Selenium+Lab2020.xlsx";
        File file = new File(filepath);
        FileInputStream fis = new FileInputStream(file);
        XSSFWorkbook myWorkBook = new XSSFWorkbook(fis);
        XSSFSheet mySheet = myWorkBook.getSheetAt(0);

        for (Row row : mySheet) {
            Iterator<Cell> cellIterator = row.cellIterator();
            String username = cellIterator.next().getStringCellValue();
            // 当遇到空行时，自动跳出
            if (username.equals("")) {
                break;
            }
            String password = cellIterator.next().getStringCellValue();
            req(username, password);
        }
    }

    private void req(String username, String password) {
        // Test name: req
        // Step # | name | target | value
        // 1 | open | http://103.120.226.190/selenium-demo/git-repo |
        driver.get("http://103.120.226.190/selenium-demo/git-repo");
        // 2 | setWindowSize | 791x824 |
        driver.manage().window().setSize(new Dimension(791, 824));
        // 3 | click | name=user_number |
        driver.findElement(By.name("user_number")).click();
        // 4 | type | name=user_number | 3017218071
        driver.findElement(By.name("user_number")).sendKeys(username);
        // 5 | click | name=password |
        driver.findElement(By.name("password")).click();
        // 6 | type | name=password | https://github.com/tianzhaotju/software_testing
        driver.findElement(By.name("password")).sendKeys(password);
        // 7 | click | css=.btn |
        driver.findElement(By.cssSelector(".btn")).click();
        String text = driver.findElement(By.xpath("/html/body/div/div/div/div/div/div/div[2]/div/form/div[5]/code")).getText();
        System.out.println(text);
        TestCase.assertEquals(password, text);
    }
}
